<?php
namespace OSC\Commands\Blueprint;

use Exception;

class ExportCommand extends AbstractBlueprintCommand
{
    public function __construct()
    {
        parent::__construct('blueprint:export', 'Export the current Omeka S instance as a blueprint');
        $this->argument('[output]', 'File to write the blueprint to (prints to stdout if omitted)');
        $this->option(
            '--include',
            'Comma-separated optional parts to export (' . implode(', ', ExportOptions::OPTIONAL_PARTS) . '); '
            . 'site-permissions: the sites\' user permissions, with the users they name'
        );
        $this->usage(
            'blueprint:export<eol/>'
            . 'blueprint:export ./site.blueprint.jsonc<eol/>'
            . 'blueprint:export ./site.blueprint.jsonc --include site-permissions'
        );
    }

    public function execute(?string $output = null, ?string $include = null): void
    {
        // validate the options before touching the instance
        $options = ExportOptions::fromInclude($include);

        $instance = $this->getOmekaInstance(false);
        if (!$instance->getStatus()->isInstalled()) {
            throw new Exception('Omeka S is not installed at this location; there is nothing to export.');
        }

        $exporter = new BlueprintExporter($instance, $this->getOmekaVersion(), $options);
        $blueprint = $exporter->export();
        $jsonc = $this->render($blueprint, $exporter->unresolvedVocabularies());

        if ($output === null) {
            $this->echo($jsonc, true);
            return;
        }

        if (file_put_contents($output, $jsonc . "\n") === false) {
            throw new Exception("Could not write the blueprint to '{$output}'.");
        }
        $this->ok("Blueprint exported to '{$output}'.", true);
    }

    /**
     * Render the blueprint as jsonc: a header comment plus pretty JSON.
     *
     * @param string[] $unresolvedVocabularies
     */
    private function render(array $blueprint, array $unresolvedVocabularies): string
    {
        $header = '// Generated by omeka-s-cli blueprint:export on ' . date('c') . ".\n"
            . "// First cut: modules, themes, vocabularies and sites; site permissions and the users they name with\n"
            . "// --include site-permissions (settings, other users and resource templates are not exported yet).\n";
        if ($unresolvedVocabularies) {
            $header .= '// These vocabularies have no source - add a "source" before deploying: '
                . implode(', ', $unresolvedVocabularies) . ".\n";
        }

        $json = json_encode($blueprint, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

        return $header . $json;
    }
}
