<?php

namespace OSC\Settings;

use Exception;
use JsonException;
use OSC\Helper\ResourceFetcher;
use Otar\JSONC;

/**
 * Read and write {@see SettingsDocument} objects as JSONC.
 *
 * Keeps the JSONC/JSON concerns and file IO out of the export and import commands: `encode`/`decode`
 * are pure (string <-> document) and unit-testable without disk, while `read`/`write` add the file
 * (or URL) IO on top.
 */
class SettingsSerializer
{
    /**
     * Render a document as JSONC: a leading comment line followed by pretty JSON.
     */
    public function encode(SettingsDocument $document): string
    {
        $json = json_encode(
            $document->toArray(),
            JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR
        );

        return "// {$document->filename()} — generated by omeka-s-cli config:export\n" . $json . "\n";
    }

    /**
     * Parse JSONC content (comments and trailing commas allowed) into a validated document.
     *
     * @param ?string $sourceLabel A name for the source, used in error messages (e.g. the filename)
     * @throws Exception When the content is not valid JSONC or not a valid settings document
     */
    public function decode(string $content, ?string $sourceLabel = null): SettingsDocument
    {
        $where = $sourceLabel !== null ? " in '{$sourceLabel}'" : '';

        try {
            $data = JSONC::decode($content, true, 512, JSON_THROW_ON_ERROR);
        } catch (JsonException $e) {
            throw new Exception("Invalid JSONC{$where}: " . $e->getMessage(), 0, $e);
        }

        if (!is_array($data)) {
            throw new Exception("Invalid settings file{$where}: expected an object.");
        }

        try {
            return SettingsDocument::fromArray($data);
        } catch (Exception $e) {
            throw new Exception("Invalid settings file{$where}: " . $e->getMessage(), 0, $e);
        }
    }

    /**
     * Fetch a document from a path or URL and decode it.
     *
     * @throws Exception When the source cannot be fetched or decoded
     */
    public function read(string $source): SettingsDocument
    {
        $content = ResourceFetcher::fetch($source);

        return $this->decode($content, basename($source));
    }

    /**
     * Encode a document and write it into the given directory, using its own filename.
     *
     * @return string The path written
     * @throws Exception When the file cannot be written
     */
    public function write(SettingsDocument $document, string $directory): string
    {
        $path = rtrim($directory, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . $document->filename();
        if (file_put_contents($path, $this->encode($document)) === false) {
            throw new Exception("Failed to write '{$path}'.");
        }

        return $path;
    }
}
